stages:
  - parse

parse:
  image: node:20.13.1
  stage: parse
  only:
    - dev
  tags:
    - eks-front
  before_script:
    - echo "${PARSER_ENV}" | tr -d '\r' > .env
    - npm install
    - npm run lint
  script:
    - npm run parse
    - npm run generate
    - npm run publish
  artifacts:
    expire_in: 1 month
    paths:
      - images
      - artifacts
      - resources/config.json
      - resources/summary.json
      - resources/cyrillicSummary.json